Wandalen/wMathConcepts

sample/SampleBoxCentered.js

The sample file to see how the centered of size function works was created.

Included Sample for Centered of size function

---

sample/BoxFromPoints.js
staging/dwtools/amath/geometric/Box.s

Sample for the function BoxFromPoints using 5 points as input. 
Also some small changes in the fromPoints() function: 
-throw_err. commented
-foor loop corrected ( points.length.length ( = undefined ) -> points.length (= 5 in this example ) )

FromPoints( box, points ) function fixed and tested in the sample BoxFromPoints.js

---

staging/dwtools/amath/geometric.test/Box.test.s

Test routine added for the function pointExpand( box, point ).

Test routine created for the pointExpand( box, point ) function

---

staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s

Test routines for the functions:
- pointContains : pointContains,
- pointRelative : pointRelative,
- pointClamp : pointClamp,
- pointDistance : pointDistance,
NOT WORKING YET

Test routines for point-related functions

---

staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s

In Box.s, in the pointContains function:
- rename .vector functions to their current name
In Box.test.s, test routine adjusted.

Test routine for pointContains fixed

---

sample/testDist.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Sphere.s

Documentation improved for box:
boxContains : boxContains,                   
boxIntersects : boxIntersects,           
boxExpand : boxExpand,                      
pointContains : pointContains,                   
pointDistance : pointDistance,               
pointClamp : pointClamp,                         
pointRelative : pointRelative,                     
pointExpand : pointExpand,                     
and pointDistance routine fixed.

pointDistance test routine and Documentationn improvements

---

sample/SampleCenterGet.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s

centerGet( box, point ) returns array
centerGet( box ) returns vector

Center get routine sample

---

staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s

Test routines and documentation written for Box: minGet and maxGet.

Box test routines minGet/maxGet

---

sample/SampleRadiusSet.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Sphere.s

Test routine and documentation written for the (Box) sizeGet routine.

Box: sizeGet test routine

---

sample/BoxFromPoints.js
sample/SampleSphereCenterGet.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Sphere.s

radiusSet test routine corrected.
Common test case for radiusSet and radiusGet routines included.

Sphere: radiusSet test routine

---

sample/SamplePlane.js
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric/Plane.s

Plane.s : Translate test routine and doc created.
Negate test routine and doc created.
Normalize test routine and doc created.

Plane routines

---

sample/SampleFrustum.js
sample/SamplePlane.js
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s

Plane.s: threePlanesIntersectionPoint function and test routine created:
It returns the intersection point of three planes. If they don´t intersect, it returns NaN.

Planes intersection

---

sample/SampleFrustum.js
sample/SamplePlane.js
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric/Frustum.s

frustumCorners and frustumIntersects functions andd test routines created.

Frustum functions

---

sample/SampleFrustum.js
staging/dwtools/amath/geometric/Frustum.s

Frustum function pointClosestPoint( frustum, point )

Frustum: pointClosestPoint function created

---

sample/SampleFrustum.js
sample/SamplePlane.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Frustum.s

Frustum function pointClosestPoint( frustum, point ) 
function corrected and test routine created

Frustum: pointClosestPoint

---

sample/SampleFrustum.js
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric/Frustum.s

boxClosestPoint test routine created, function corrected, and other functions improved

frustum: boxClosestPoint/ sphereClosestPoint

---

sample/SampleEuler.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Euler.s

matrix -> euler -> matrix test routine

Euler: toMatrix2 test routine

---

sample/SampleEuler.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Sphere.s

Naming corrections in Frustum.s

Naming corrections

---

sample/SampleEuler.js
sample/SampleEulerRoutine.js
sample/SampleTestEuler.js
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric/Euler.s

Right now working for quadrants 0 and 2, and angles 2 and 3 equal.
Next: fix issue for quadrants 1 and 3.
Increase test to three different angles.

Euler.test.s: eulerToQuatToEulerToQuat test routine

---

staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Sphere.s

- representFullCoverageSlow improved.

Euler.test.s: representFullCoverage

---

sample/SampleAxisAngle.js
sample/SampleEuler.js
sample/SampleEulerAxisAngle.js
sample/SampleFrustum.js
sample/SampleQuatMatrix.js
staging/dwtools/amath/geometric.test/AxisAndAngle.test.s
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Quat.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/AxisAndAngle.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Quat.s
staging/dwtools/amath/geometric/Sphere.s

- _.frustum.pointClosestPoint corrections
- toQuat2 improved
- toAxisAndAngle2 in progress
- fromAxisAndAngle2 in progress

Euler converters

---

sample/SampleBoxCentered.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Sphere.s

_.box.boxIntersects corrected
_.box.boxDistance created

_.box routines

---

sample/SampleBoxCentered.js
sample/SampleFrustum.js
sample/SampleSphere.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Sphere.s

_.box.sphereExpand method and test routine
_.box.planeDistance method and test routine
_.box.planeClosestPoint method and test routine
_.box.planeExpand method and test routine
_.box.frustumContains method and test routine
_.box.frustumDistance method and test routine
_.box.frustumClosestPoint method and test routine
_.box.frustumExpand method and test routine
_.sphere.pointContains and _.sphere.pointClosestPoint test routines
_.sphere.boxContains method and test routine
_.sphere.boxClosestPoint method and test routine
_.sphere.sphereContains method and test routine
_.sphere.sphereDistance method and test routine
_.sphere.sphereClosestPoint method and test routine
_.sphere.planeClosestPoint method and test routine
_.sphere.planeExpand method and test routine
_.sphere.frustumContains …

Box.s methods and test routines

---

sample/SampleFrustum.js
sample/SamplePlane.js
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s

_.frustum.planeDistance method and test routine
_.frustum.planeClosestPoint method and test routine (+ improvements in other *ClosestPoint methods)
_.frustum.frustumContains method and test routine
_.frustum.frustumDistance method and test routine
_.frustum.frustumClosestPoint method and test routine
_.plane.pointContains method and test routine
_.plane.boxClosestPoint method and test routine
_.plane.sphereClosestPoint method and test routine
_.plane.planeIntersects method and test routine
_.plane.planeDistance method and test routine
_.plane.frustumClosestPoint method and test routine

Frustum.s methods and test routines

---

sample/SampleBoxCentered.js
sample/SampleEuler.js
sample/SampleFrustum.js
sample/SamplePlane.js
sample/SampleSphere.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Euler.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Quat.test.s
staging/dwtools/amath/geometric/AxisAndAngle.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Quat.s
staging/dwtools/amath/geometric/Sphere.s
staging/dwtools/amath/geometric/aConcepts.s

var -> let in non-test files:
- Box.s
- Sphere.s
- Plane.s
- Frustum.s
- Euler.s
- Quat.s
- AxisAndAngle.s
Duplicated methods:
- Box.s:
- _.box.sphereIntersects
- _.box.planeIntersects
- _.box.frustumIntersects
- Sphere.s:
- _.sphere.boxDistance
- _.sphere.planeIntersects
- _.sphere.planeDistance
- _.frustum.frustumIntersects
- Plane.s:
- _.plane.boxDistance
- _.plane.frustumIntersects
- _.plane.frustumDistance
- Frustum.s:
- _.frustum.boxDistance
- _.frustum.sphereDistance
Remaining descriptions:
- Box.s
_.box.translate method modified

wMathConcepts changes

---

doc/RayUsage.md
sample/SampleFrustum.js
sample/SampleRay.js
sample/SampleSphere.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Ray.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Ray.s
staging/dwtools/amath/geometric/Sphere.s

Avoid toArray: 
- Box.s
- Sphere.s 
- Plane.s
- Frustum.s
Remove .slice():
- Box.s
- Sphere.s
- Plane.s
- Frustum.s
Remove undef input for some routines:
- Box.s
- Sphere.s
- Plane.s
Ray.s functions and test routines:
- _.ray.is function and test routine
- _.ray.dimGet function
- _.ray.originGet function
- _. ray.directionGet function

General Corrections

---

doc/RayUsage.md
sample/SampleBoxCentered.js
sample/SampleRay.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Ray.test.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Quat.s
staging/dwtools/amath/geometric/Ray.s
staging/dwtools/amath/geometric/Sphere.s

- Naming corrections applied.
- Ray.s:
- _.ray.rayAt method modified and test routine added.
- _.ray.rayParallel method modified and test routine added.
- _.ray.rayIntersectionFactors method modified and test routine added.
- _.ray.rayIntersectionPoints method modified and test routine added.
- _.ray.rayIntersectionPoint method modified and test routine added.
- _.ray.rayIntersectionPointAccurate method modified and test routine added.

Naming corrections and Ray.s methods

---

sample/SampleRay.js
sample/SampleSpace.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Ray.test.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Ray.s

_.ray.rayIntersectionFactors using _.Space
Adjustments in test routines and related methods.:
- rayIntersectionPoints : rayIntersectionPoints
- rayIntersectionPoint : rayIntersectionPoint
- rayIntersectionPointAccurate : rayIntersectionPointAccurate
_.ray.pointContains method and test routine ( + some CC corrections in Box.test.s )
_.ray.getFactor method and test routine ( + some CC corrections in Box.test.s )
_.ray.pointDistance method and test routine 
_.ray.pointClosestPoint method and test routine 
_.ray.boxIntersects method and test routine  
_.ray.boxDistance method and test routine
_.ray.boxClosestPoint method and test routine
_.ray.sphereIntersects method and test routine
_.ray.sphereDistance method and test routine
_.ray.sphereClosestPoint method and test routine …

Ray.s functions

---

sample/SampleBoxCentered.js
sample/SampleFrustum.js
sample/SamplePlane.js
sample/SampleRay.js
sample/SampleSegment.js
sample/SampleSphere.js
sample/sampleLine.js
staging/dwtools/amath/geometric.test/Box.test.s
staging/dwtools/amath/geometric.test/Frustum.test.s
staging/dwtools/amath/geometric.test/Line.test.s
staging/dwtools/amath/geometric.test/Plane.test.s
staging/dwtools/amath/geometric.test/Ray.test.s
staging/dwtools/amath/geometric.test/Segment.test.s
staging/dwtools/amath/geometric.test/Sphere.test.s
staging/dwtools/amath/geometric/AxisAndAngle.s
staging/dwtools/amath/geometric/Box.s
staging/dwtools/amath/geometric/Euler.s
staging/dwtools/amath/geometric/Frustum.s
staging/dwtools/amath/geometric/Line.s
staging/dwtools/amath/geometric/Plane.s
staging/dwtools/amath/geometric/Quat.s
staging/dwtools/amath/geometric/Ray.s
staging/dwtools/amath/geometric/Segment.s
staging/dwtools/amath/geometric/Sphere.s
staging/dwtools/amath/geometric/aConcepts.s

Ray.s:
- _.ray.frustrumIntersects method and test routine.
- _.ray.rayDistance method and test routine.
- _.ray.rayClosestPoint method and test routine.
- _.ray.frustumClosestPoint method and test routine.
- _.ray.frustumDistance method and test routine.
- _.ray.lineClosestPoint method and test routine.
- segment related methods.
Box.s:
- _.box.cornersGet method and test routine.
- _.box.rayIntersects method.
- _.box.rayDistance method.
- _.box.rayClosestPoint method and test routine.
- line related methods.
- segment related methods.
Sphere.s:
- _.sphere.rayIntersects method.
- _.sphere.rayDistance method.
- _.sphere.rayClosestPoint method and test routine.
- line related methods.
- segment related methods.
Plane.s:
- _.plane.rayIntersects method.
- _.plane.rayDistance method.
- …

Ray, Line and Segment methods
